#!/usr/bin/env python3

import sys
import json
from getpass import getpass
from urllib import request
from urllib.parse import urlencode

if len(sys.argv) < 3:
    print("Usage: {} CLIENT USER [PASSWORD]".format(sys.argv[0]))
    sys.exit(1)

client = sys.argv[1]
user = sys.argv[2]

if len(sys.argv) >= 4:
    password = sys.argv[3]
else:
    password = getpass("Password: ")

headers = {
    'X-Plex-Client-Identifier': client,
    'X-Plex-Product': client,
    'X-Plex-Version': '0.0.1',
}

data = urlencode({
    'user[login]': user,
    'user[password]': password,
}).encode('utf-8')

req = request.Request("https://plex.tv/users/sign_in.json", data=data, headers=headers)
res = request.urlopen(req)

raw = res.read().decode('utf-8')
data = json.loads(raw)
print(data['user']['authentication_token'])

